name: kn_class
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - astropy
  - jupyter
  - imbalanced-learn
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu124
    - torchvision --index-url https://download.pytorch.org/whl/cu124
    - seaborn
    - pyarrow
    - speclite
